pub const APP_NAME: &str = "swarm";
pub const APP_VERSION: &str = env!("CARGO_PKG_VERSION");
pub const IPC_ADDRESS: &str = "127.0.0.1:44287";
pub const IPC_MESSAGE_BYTES_MAX: u64 = 1 << 20;
pub const IPC_PATH_COUNT_MAX: u32 = 100;
pub const IPC_READ_TIMEOUT_MS: u64 = 2_000;
pub const LINE_COUNT_BYTES_MAX: u64 = 1 << 30;
pub const MESSAGE_COUNT_MAX: u32 = 256;
pub const MESSAGE_QUEUE_COUNT_MAX: u32 = 4_096;
pub const OUTPUT_BYTES_MAX: u64 = 256 << 20;
pub const PRESET_COUNT_MAX: u32 = 4_096;
pub const SESSION_COUNT_MAX: u32 = 4_096;
pub const TITLE_BAR_HEIGHT_PIXELS: f32 = 32.0;
pub const TITLE_BUTTON_WIDTH_PIXELS: f32 = 46.0;
pub const TOAST_FADE_SECONDS: f32 = 0.3;
pub const TOAST_LIFETIME_SECONDS: f32 = 3.0;
pub const TREE_NODE_COUNT_MAX: u32 = 1_000_000;
pub const UI_SCALE_FALLBACK: f32 = 1.3;
pub const UI_SCALE_MAX: f32 = 3.0;
pub const UI_SCALE_MIN: f32 = 0.5;
pub const WALK_FILE_COUNT_MAX: u32 = 1_000_000;
pub const WALK_QUEUE_COUNT_MAX: u32 = 4_096;
pub const WORKER_QUEUE_COUNT_MAX: u32 = 64;
const _: () = assert!(IPC_PATH_COUNT_MAX > 0);
const _: () = assert!(MESSAGE_COUNT_MAX <= MESSAGE_QUEUE_COUNT_MAX);
const _: () = assert!(TOAST_FADE_SECONDS * 2.0 <= TOAST_LIFETIME_SECONDS);
const _: () = assert!(UI_SCALE_MIN < UI_SCALE_FALLBACK);
const _: () = assert!(UI_SCALE_FALLBACK < UI_SCALE_MAX);
